#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orcldb-pvcu1
  labels:
    app: oracledb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: oci
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orcldb-pvcu2
  labels:
    app: oracledb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: oci
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orcldb-pvcu3
  labels:
    app: oracledb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: oci
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orcldb-pvcu4
  labels:
    app: oracledb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: oci
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orcldb
  labels:
    app: oracledb
spec:
  selector:
    matchLabels:
      app: oracledb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: oracledb
    spec:
      containers:
      - image: javiermugueta/orcl
#      - image: fra.ocir.io/telefonicacloud2/atrepo/orcldb:latest
#      - image: container-registry.oracle.com/database/standard
        name: orcldb
        ports:
        - containerPort: 1521
          name: orcldb
        volumeMounts:
        - name: orcldb-pers-stor1
          mountPath: /u01
        - name: orcldb-pers-stor2
          mountPath: /u02
        - name: orcldb-pers-stor3
          mountPath: /u03
        - name: orcldb-pers-stor4
          mountPath: /u04
      imagePullSecrets:
        - name: orclcred
      volumes:
        - name: orcldb-pers-stor1
          persistentVolumeClaim:
            claimName: orcldb-pvcu1
        - name: orcldb-pers-stor2
          persistentVolumeClaim:
            claimName: orcldb-pvcu2
        - name: orcldb-pers-stor3
          persistentVolumeClaim:
            claimName: orcldb-pvcu3
        - name: orcldb-pers-stor4
          persistentVolumeClaim:
            claimName: orcldb-pvcu4
---
apiVersion: v1
kind: Service
metadata:
 name: oracledb
spec:
 type: LoadBalancer
 selector:
   app: oracledb
 ports:
   - name: client
     protocol: TCP
     port: 1521
     nodePort: 31521
 selector:
   app: oracledb
