apiVersion: apps/v1
kind: Deployment
metadata:
  name: orcldb
  labels:
    app: oracle
spec:
  selector:
    matchLabels:
      app: oracle
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: oracle
    spec:
      containers:
       - image: javiermugueta/orcl
#      - image: fra.ocir.io/telefonicacloud2/atrepo/orcldb:latest
#      - image: container-registry.oracle.com/database/standard
        name: orcldb
        ports:
        - containerPort: 1521
          name: orcldb
#        volumeMounts:
#        - name: orcldb-pers-stor1
#          mountPath: /ORCL
#       - name: orcldb-pers-stor2
#          mountPath: /home/oracle/
#      imagePullSecrets:
#        - name: orclcred
#      volumes:
#        - name: orcldb-pers-stor1
#          persistentVolumeClaim:
#            claimName: orcldb-pvc1
#        - name: orcldb-pers-stor2
#          persistentVolumeClaim:
#            claimName: orcldb-pvc2




  
