#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orcldb-pvc1
  labels:
    app: oracledb
#spec:
#  accessModes:
#  - ReadWriteOnce
#  resources:
#    requests:
#      storage: 200Gi
#  storageClassName: oci
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orcldb-pvc2
  labels:
    app: oracledb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: oci
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orcldb
  labels:
    app: oracledb
spec:
  selector:
    matchLabels:
      app: oracledb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: oracledb
    spec:
      containers:
#       - image: javiermugueta/orcl
      - image: fra.ocir.io/telefonicacloud2/atrepo/orcldb:latest
#      - image: container-registry.oracle.com/database/standard
        name: orcldb
        ports:
        - containerPort: 1521
          name: orcldb
        volumeMounts:
        - name: orcldb-pers-stor1
          mountPath: /opt/oracle
#       - name: orcldb-pers-stor2
#          mountPath: /home/oracle/
      imagePullSecrets:
        - name: orclcred
      volumes:
        - name: orcldb-pers-stor1
          persistentVolumeClaim:
            claimName: orcldb-pvc1
#        - name: orcldb-pers-stor2
#          persistentVolumeClaim:
#            claimName: orcldb-pvc2
---
apiVersion: v1
kind: Service
metadata:
 name: oracledb
spec:
 type: LoadBalancer
 selector:
   app: oracledb
 ports:
   - name: client
     protocol: TCP
     port: 1521
     nodePort: 31521
 selector:
   app: oracledb
